# Generated by Django 4.2.11 on 2024-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakecms', '0002_profile_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='body_text',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='footer_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='head_color',
            field=models.CharField(max_length=7),
        ),
    ]
